name: Build and Release Native File Mover

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

env:
  CARGO_TERM_COLOR: always

# https://jon.sprig.gs/blog/post/2442

permissions:
  contents: write

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - uses: softprops/action-gh-release@v2

  build_release:
    name: Build Releases
    needs: create_release
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
        - os: ubuntu-latest
          name: linux
          ext: ""
        - os: windows-latest
          name: windows
          ext: ".exe"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cd native && cargo build --verbose --release

      - name: Rename Binary
        shell: bash
        run: |
          VERSION=${GITHUB_REF_NAME}
          BIN_NAME="file-mover-${VERSION}-${{ matrix.name }}${{ matrix.ext }}"
          mv native/target/release/file-mover${{ matrix.ext }} $BIN_NAME
          echo "BIN_NAME=$BIN_NAME" >> $GITHUB_ENV

      - uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.BIN_NAME }}
